server:
  port: 10002
spring:
  application:
    name: @project.artifactId@
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    instance-id: @project.artifactId@
#feign:
#  circuitbreaker:
#    enabled: true
